### ISSUE TITLE
añadir en el codigo

### ISSUE THREAD

**Issue by bravelord** [DaWy/htcmania_poster#1]
Añade al script:

from selenium.webdriver.firefox.firefox_binary import FirefoxBinary

binary = FirefoxBinary('localizacion firefox en el equipo')
profile = webdriver.FirefoxProfile()
path = "localizacion geckodriver en carpeta python" # C:\\python27\\geckodriver.exe

browser = webdriver.Firefox(executable_path=path,firefox_profile=profile,firefox_binary=binary)

para que reconozca el Firefox y se pueda conectar

**Comment by DaWy** [comment]
HE eliminado PhantomJS y selenium ya que no es soportado... Y he separado la parte de la autentificación en otro fichero.

Ahora no hace falta tener selenium y phantomjs instalado, solo el Chrome + Chromedriver. 

Si quieres hacer una modificacion usando firefox te animo a hacer un pull request :)
